#include "RNACMB.hpp"

/* Set Global Defaults */
uint_fast64_t rna_dat_tracker = 0;
uint_fast64_t steric_clash_checks_attempted = 0;
uint_fast64_t steric_clash_checks_skipped = 0;

char GLOBAL_INPUT_SEQUENCE[100];
char GLOBAL_INPUT_INDICES[100];
char GLOBAL_INPUT_FILE[100];
char GLOBAL_OUTPUT_FILE[100];
char GLOBAL_IO_ACTION[5] = "w";

bool GLOBAL_RUN_COMBINATORIAL = false;
bool GLOBAL_RUN_BUILD_STRUCTURE = false;
bool GLOBAL_RUN_BUILD_STRUCTURE_LIST = false;
bool GLOBAL_RUN_BUILD_STRUCTURE_LIST_TESTING = false;
bool GLOBAL_WRITE_COORDINATES = false;
uint_fast64_t GLOBAL_STRUCTURE_LIMIT_COUNT = 1;
//bool GLOBAL_PERFORM_HAIRPIN_CHECK = false;
//bool GLOBAL_PERFORM_HBOND_CHECK = false;
STRUCTCHECK_TYPE GLOBAL_PERFORM_STRUCTCHECK = NONE;

double GLOBAL_RMSD_LIMIT = DEFAULT_RMSD_LIMIT;
double GLOBAL_WC_RMSD_LIMIT = DEFAULT_WC_RMSD_LIMIT;
double GLOBAL_SCC_LIMIT = DEFAULT_STERIC_CLASH_COM_DISTANCE_LIMIT;
int **GLOBAL_INPUT_INDICES_LIST;
char LIBRARY_FILENAME_PROTOTYPE[100];     // = "../AGAAAU_test/XX_library_combined.txt";
char WATSON_CRICK_LIBRARY_PROTOTYPE[100]; // = "../AGAAAU_test/WC_XX_library.txt";
